# Generated by Django 3.2.7 on 2023-01-25 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_established_year',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_no_of_doctors',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_no_of_nurses',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_company_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_company_established_year',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_company_phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_company_website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_a_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_an_insurance_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
