# Generated by Django 3.2.7 on 2023-01-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20230125_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacion_address', models.CharField(max_length=50000)),
                ('npi', models.CharField(max_length=50000)),
            ],
        ),
    ]
