# Generated by Django 3.2.7 on 2023-01-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='npi',
            new_name='ipn',
        ),
    ]
