# Generated by Django 3.2.7 on 2023-01-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_npi_block_ipn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacion_address', models.CharField(max_length=50000)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.block')),
            ],
        ),
    ]
