# Generated by Django 3.2.7 on 2023-02-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_blockamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='sherlock.jpg', upload_to='policy')),
                ('name', models.CharField(blank=True, default='', max_length=5000)),
                ('description', models.CharField(blank=True, default='', max_length=50000)),
                ('type', models.CharField(blank=True, default='', max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
