# Generated by Django 3.2.7 on 2023-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.CharField(default='', max_length=50000),
            preserve_default=False,
        ),
    ]
