# Generated by Django 3.2.7 on 2023-03-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20230322_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
