# Generated by Django 3.2.7 on 2023-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_block_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ipn',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
