# Generated by Django 3.2.7 on 2023-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_notification_ipn'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
